//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace lab8_mvc_net.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class compañiasdeenvios
    {
        public int idCompañiaEnvios { get; set; }
        public string nombreCompañia { get; set; }
        public string telefono { get; set; }
    }
}
